### ISSUE TITLE
设置不可移动集合后，移动崩溃

### ISSUE THREAD

**Issue by lintongSD** [yitezh/collectCell-#1]
添加了3组数据，打开设置不可移动集合到其它分组后app崩溃，请问有办法避免这种情况吗

**Comment by yitezh** [comment]
> 添加了3组数据，打开设置不可移动集合到其它分组后app崩溃，请问有办法避免这种情况吗

不好意思，没太看明白，是指多section的情况下交换出错吗？？

**Comment by lintongSD** [comment]
是的，将第二组数据移动到第一组时崩溃了

多section情况下能指定第一组元素可交换，其它组禁止交换，这个需求可以满足吗

**Comment by yitezh** [comment]
搜一下这个条件判断： if([disableArray containsObject:indexPath])有两处，把你的条件加进去，
如果你只有section为0才能操作，那就改成：if([disableArraycontainsObject:indexPath]||indexPath.section!=0)

**Comment by yitezh** [comment]
> 是的，将第二组数据移动到第一组时崩溃了
> 
> 多section情况下能指定第一组元素可交换，其它组禁止交换，这个需求可以满足吗

我给的方法可以了吗？可以的话这个issue关掉了。

**Comment by lintongSD** [comment]
可以了，感谢大佬百忙中抽空回复

**Comment by yitezh** [comment]
> 可以了，感谢大佬百忙中抽空回复

没事，我也是菜鸟……
